owner: spare-technologies
repo: status-test
sites:
  - name: Google
    url: https://www.google.com
  - name: GitHub
    url: https://github.com
assignees:
  - vnairkronovate
status-website:
  baseUrl: /status-test
  name: Status Test Debug
  theme: light
